### PR TITLE
Refactor logoout

### PR DESCRIPTION
**Pull request by shashikantmaurya0007**
feature:added logout feature and updated the redirecting link

### CODE REVIEW

**Review by JatuFaique — APPROVED** [review]
Looks good to merge, All the best

**Review by ravikumar0403 — APPROVED** [review]
Looks good to merge

**Review by yashpatel1797 — APPROVED** [review]
Looks good to merge.

**Review by SukanyaSen530 — COMMENTED** [review]
Typo - Log Out - "logoout"

**Review by shivamSspirit — COMMENTED** [review]
good work

**Pull request merged**
